name: Deploy Hugo Site with gh-pages

on:
  push:
    branches:
      - master

    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v1
      - name: Checkout
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.1
        with:
          hugo-version: "0.58.3"
      - name: Prepare Hugo
        run: |
          git submodule sync && git submodule update --init
      - name: Start Deployment
        run: |
          echo "Github Action Creds"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          chmod +x ./publish_to_ghpages.sh
          ./publish_to_ghpages.sh

